name: Create a release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Download and install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run semantic-release
        run: npx semantic-release
on:
  push:
    branches:
      - main
